# mini.ideidlyabiznesa1913.ru
# Этап 1 — заглушка 503. Будет наполнено на соответствующем Этапе.

server {
    server_name mini.ideidlyabiznesa1913.ru;

    error_page 503 /503.html;
    location = /503.html {
        root /var/www/_503;
        internal;
    }
    location / {
        return 503;
    }

    access_log /var/log/nginx/mini.access.log;
    error_log /var/log/nginx/mini.error.log;

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/inna.ideidlyabiznesa1913.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/inna.ideidlyabiznesa1913.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

# После Этапа 1 (SSL получен) — раскомментировать HTTPS-блок аналогично inna.conf


server {
    if ($host = mini.ideidlyabiznesa1913.ru) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;
    server_name mini.ideidlyabiznesa1913.ru;
    return 404; # managed by Certbot


}